### ISSUE TITLE
cursor.map stopped working?

### ISSUE THREAD

**Issue by landland** [arunoda/meteor-find-faster#3]
Hey Arunoda, just thought I'd give your new package a go and I encountered an issue. For some reason I can't do this anymore.

```
emails = RawEmails.find({}).map(function(raw) {
                        return 'hi: ' + raw.email;
                    });
console.log("emails are: ", emails);
return emails;
```

Even if I try `.find` or `.findFaster`, the map doesn't work. I've verified that when I remove find-faster then it does work. Actually, with find-faster installed, I don't even get the `console.log`. However, with find-faster removed, I get the console printout.

**Comment by arunoda** [comment]
have you applied find-faster to any other places, which like observers?
Is it possible to have a minimal repo?

**Comment by landland** [comment]
yeah, it was working great - and noticeably faster, in other places. it's in a big app. let me see if i have time to make a minimal repo.

**Comment by arunoda** [comment]
wait. It had a bug. I fixed it. Try updating now.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by landland** [comment]
Getting this

√ find-faster
    tag: https://github.com/arunoda/meteor-find-faster.git#v0.1.1
ERROR: 1 Command failed: error: pathspec 'v0.1.1' did not match any file(s) known to git.

STDOUT:

STDERR: error: pathspec 'v0.1.1' did not match any file(s) known to git.

/usr/local/lib/node_modules/meteorite/lib/sources/git.js:181
            self.checkoutType + ": " + (self.commit || self.head);
                                     ^
There was a problem checking out tag: v0.1.1

**Comment by landland** [comment]
nevermind. good now. ok testing

**Comment by arunoda** [comment]
cool.

**Comment by landland** [comment]
all fixed. you're the man :)

**Comment by arunoda** [comment]
No problem.
